let vocab = {
    "Guten Morgen": "Bom dia",
    "Guten Abend": "Boa noite",
    "Gute Nacht": "Bonne noite(de sono)",
    "Was machst du?": "O que você faz?",
    "Viel Glück!": "Boa sorte!",
    "Bis Bald!": "te vejo em breve",
    "Ich bin verloren": "Estou perdido(a)",
    "Ich bin hier": "Eu estou aqui",
    "Das ist nicht mein Problem": "Isso não é problema meu",
    "Ich bin einverstanden": "concordo",
    "Wie spät ist es?": "Que horas são?",
    "Ich brauche Hilfe": "Eu preciso de ajuda",
    "Gibt es hier WLAN?": "Aqui tem Wi-fi?",
    "Ich habe es vergessen": "Eu esqueci",
    "Schau mal!": "Olhe!",
    "Das ist schön": "Isso é lindo",
    "Ich bin beschäftigt": "Eu estou ocupado(a)",
    "Es ist Zeit zu gehen": "Está na hora de ir",
    "Ich bin froh": "Estou feliz",
}